### ISSUE TITLE
请教您关于最后预测的问题即执行bash scripts/predict.sh

### ISSUE THREAD

**Issue by sujingxd** [thu-coai/AutoCAD#1]
请问下运行这个环节（bash scripts/predict.sh）的目的是对前面一步骤（4）Generate Counterfactuals生成的反事实进行预测吗？如果这样的话是不是在（bash scripts/predict.sh）过程中输入文件不应该是train.json( or dev.joson)而应该是train_generate.json（dev_generate.json）文件（它们是前面一步生成的反事实数据）。此外在执行tools/highlight.py文件后生成的train_cad.json（dev_cad.json）文件的作用是什么？后面一直没有直接显示说明如何使用？

**Comment by Jiaxin-Wen** [comment]
脚本里具体的文件名需要根据实际情况进行修改

1. tools/highlight.py生成的文件是用来训练generator的
2. 是的，bash scripts/predict.sh的输入文件是train_generate.json（前一步生成的反事实数据）
